
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Bestiary : Luban.BeanBase
{
    public Bestiary(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name_loc_key"].IsString) { throw new SerializationException(); }  NameLocKey = _buf["name_loc_key"]; }
        NameLocKey_Ref = null;
        { if(!_buf["cha_class"].IsNumber) { throw new SerializationException(); }  ChaClass = (ChaClassType)_buf["cha_class"].AsInt; }
        ChaClass_Ref = null;
        { if(!_buf["core_attri"].IsObject) { throw new SerializationException(); }  CoreAttri = ChaCoreAttributes.DeserializeChaCoreAttributes(_buf["core_attri"]);  }
        { if(!_buf["res_prefab"].IsObject) { throw new SerializationException(); }  ResPrefab = ResPack.DeserializeResPack(_buf["res_prefab"]);  }
    }

    public static Bestiary DeserializeBestiary(JSONNode _buf)
    {
        return new Bestiary(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string NameLocKey;
    public LocGame NameLocKey_Ref;
    /// <summary>
    /// 职业
    /// </summary>
    public readonly ChaClassType ChaClass;
    public ChaClass ChaClass_Ref;
    public readonly ChaCoreAttributes CoreAttri;
    /// <summary>
    /// 预制体资源名
    /// </summary>
    public readonly ResPack ResPrefab;
   
    public const int __ID__ = 1907629411;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        NameLocKey_Ref = tables.TbLocGame.GetOrDefault(NameLocKey);
        ChaClass_Ref = tables.TbChaClass.GetOrDefault(ChaClass);
        CoreAttri?.ResolveRef(tables);
        ResPrefab?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameLocKey:" + NameLocKey + ","
        + "chaClass:" + ChaClass + ","
        + "coreAttri:" + CoreAttri + ","
        + "resPrefab:" + ResPrefab + ","
        + "}";
    }
}

}

