
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ChaClass : Luban.BeanBase
{
    public ChaClass(JSONNode _buf) 
    {
        { if(!_buf["class_type"].IsNumber) { throw new SerializationException(); }  ClassType = (ChaClassType)_buf["class_type"].AsInt; }
        { if(!_buf["formation"].IsNumber) { throw new SerializationException(); }  Formation = (ChaFormation)_buf["formation"].AsInt; }
    }

    public static ChaClass DeserializeChaClass(JSONNode _buf)
    {
        return new ChaClass(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly ChaClassType ClassType;
    /// <summary>
    /// 站位类型
    /// </summary>
    public readonly ChaFormation Formation;
   
    public const int __ID__ = 1457495644;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "classType:" + ClassType + ","
        + "formation:" + Formation + ","
        + "}";
    }
}

}

