
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 角色核心属性
/// </summary>
public sealed partial class ChaCoreAttributes : Luban.BeanBase
{
    public ChaCoreAttributes(JSONNode _buf) 
    {
        { if(!_buf["Might"].IsNumber) { throw new SerializationException(); }  Might = _buf["Might"]; }
        { if(!_buf["Dexterity"].IsNumber) { throw new SerializationException(); }  Dexterity = _buf["Dexterity"]; }
        { if(!_buf["Intellect"].IsNumber) { throw new SerializationException(); }  Intellect = _buf["Intellect"]; }
        { if(!_buf["Faith"].IsNumber) { throw new SerializationException(); }  Faith = _buf["Faith"]; }
        { if(!_buf["Constitution"].IsNumber) { throw new SerializationException(); }  Constitution = _buf["Constitution"]; }
        { if(!_buf["Wisdom"].IsNumber) { throw new SerializationException(); }  Wisdom = _buf["Wisdom"]; }
    }

    public static ChaCoreAttributes DeserializeChaCoreAttributes(JSONNode _buf)
    {
        return new ChaCoreAttributes(_buf);
    }

    /// <summary>
    /// 力量
    /// </summary>
    public readonly int Might;
    /// <summary>
    /// 敏捷
    /// </summary>
    public readonly int Dexterity;
    /// <summary>
    /// 智慧
    /// </summary>
    public readonly int Intellect;
    /// <summary>
    /// 信仰
    /// </summary>
    public readonly int Faith;
    /// <summary>
    /// 体质
    /// </summary>
    public readonly int Constitution;
    /// <summary>
    /// 感知
    /// </summary>
    public readonly int Wisdom;
   
    public const int __ID__ = 235652594;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Might:" + Might + ","
        + "Dexterity:" + Dexterity + ","
        + "Intellect:" + Intellect + ","
        + "Faith:" + Faith + ","
        + "Constitution:" + Constitution + ","
        + "Wisdom:" + Wisdom + ","
        + "}";
    }
}

}

