
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 角色职业
    /// </summary>
    public enum ChaClassType
    {
        /// <summary>
        /// 战士
        /// </summary>
        Warrior = 1,
        /// <summary>
        /// 圣骑士
        /// </summary>
        Paladin = 2,
        /// <summary>
        /// 牧师
        /// </summary>
        Cleric = 3,
        /// <summary>
        /// 法师
        /// </summary>
        Wizard = 4,
        /// <summary>
        /// 猎人
        /// </summary>
        Hunter = 5,
        /// <summary>
        /// 游荡者
        /// </summary>
        Rogue = 6,
        /// <summary>
        /// 巫师
        /// </summary>
        Sorcerer = 7,
    }

} 

