
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 阵型站位
    /// </summary>
    [System.Flags]
    public enum ChaFormation
    {
        /// <summary>
        /// 近战
        /// </summary>
        melee = 1,
        /// <summary>
        /// 远程
        /// </summary>
        range = 2,
        /// <summary>
        /// 全能
        /// </summary>
        melee_range = 3,
    }

} 

