
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Character : Luban.BeanBase
{
    public Character(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name_loc_key"].IsString) { throw new SerializationException(); }  NameLocKey = _buf["name_loc_key"]; }
        { if(!_buf["desc_loc_key"].IsString) { throw new SerializationException(); }  DescLocKey = _buf["desc_loc_key"]; }
    }

    public static Character DeserializeCharacter(JSONNode _buf)
    {
        return new Character(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string NameLocKey;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string DescLocKey;
   
    public const int __ID__ = -726803703;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameLocKey:" + NameLocKey + ","
        + "descLocKey:" + DescLocKey + ","
        + "}";
    }
}

}

