
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 伤害属性
    /// </summary>
    public enum ElementType
    {
        /// <summary>
        /// 水属性
        /// </summary>
        Water = 1,
        /// <summary>
        /// 火属性
        /// </summary>
        Fire = 2,
        /// <summary>
        /// 风属性
        /// </summary>
        Wind = 3,
        /// <summary>
        /// 土属性
        /// </summary>
        Earth = 4,
        /// <summary>
        /// 圣属性
        /// </summary>
        Sacredness = 5,
        /// <summary>
        /// 暗属性
        /// </summary>
        Darkness = 6,
    }

} 

