
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Equipment : Luban.BeanBase
{
    public Equipment(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (EquipmentType)_buf["type"].AsInt; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
        { if(!_buf["core_attri_addtion"].IsObject) { throw new SerializationException(); }  CoreAttriAddtion = ChaCoreAttributes.DeserializeChaCoreAttributes(_buf["core_attri_addtion"]);  }
    }

    public static Equipment DeserializeEquipment(JSONNode _buf)
    {
        return new Equipment(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 装备类型
    /// </summary>
    public readonly EquipmentType Type;
    /// <summary>
    /// 重量
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 力量
    /// </summary>
    public readonly ChaCoreAttributes CoreAttriAddtion;
   
    public const int __ID__ = -1214642834;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        CoreAttriAddtion?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "weight:" + Weight + ","
        + "coreAttriAddtion:" + CoreAttriAddtion + ","
        + "}";
    }
}

}

