
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 装备类型
    /// </summary>
    public enum EquipmentType
    {
        /// <summary>
        /// 头部
        /// </summary>
        Head = 1,
        /// <summary>
        /// 身体
        /// </summary>
        Body = 2,
        /// <summary>
        /// 腿部
        /// </summary>
        Leg = 3,
        /// <summary>
        /// 宝物
        /// </summary>
        Treasure = 4,
        /// <summary>
        /// 单手武器
        /// </summary>
        SingleHanded = 5,
        /// <summary>
        /// 双手武器
        /// </summary>
        TwoHanded = 6,
    }

} 

