
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbAudio TbAudio {get; }
    public TbLocUi TbLocUi {get; }
    public TbLocGame TbLocGame {get; }
    public TbCyclopedia TbCyclopedia {get; }
    public TbPartner TbPartner {get; }
    public TbBestiary TbBestiary {get; }
    public TbEquipment TbEquipment {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbAudio = new TbAudio(loader("tbaudio"));
        TbLocUi = new TbLocUi(loader("tblocui"));
        TbLocGame = new TbLocGame(loader("tblocgame"));
        TbCyclopedia = new TbCyclopedia(loader("tbcyclopedia"));
        TbPartner = new TbPartner(loader("tbpartner"));
        TbBestiary = new TbBestiary(loader("tbbestiary"));
        TbEquipment = new TbEquipment(loader("tbequipment"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbAudio.ResolveRef(this);
        TbLocUi.ResolveRef(this);
        TbLocGame.ResolveRef(this);
        TbCyclopedia.ResolveRef(this);
        TbPartner.ResolveRef(this);
        TbBestiary.ResolveRef(this);
        TbEquipment.ResolveRef(this);
    }
}

}
