
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbChaClass
{
    private readonly System.Collections.Generic.Dictionary<ChaClassType, ChaClass> _dataMap;
    private readonly System.Collections.Generic.List<ChaClass> _dataList;
    
    public TbChaClass(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<ChaClassType, ChaClass>();
        _dataList = new System.Collections.Generic.List<ChaClass>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ChaClass _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ChaClass.DeserializeChaClass(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ClassType, _v);
        }
    }

    public System.Collections.Generic.Dictionary<ChaClassType, ChaClass> DataMap => _dataMap;
    public System.Collections.Generic.List<ChaClass> DataList => _dataList;

    public ChaClass GetOrDefault(ChaClassType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ChaClass Get(ChaClassType key) => _dataMap[key];
    public ChaClass this[ChaClassType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

