
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbCyclopedia
{
    private readonly System.Collections.Generic.Dictionary<int, Cyclopedia> _dataMap;
    private readonly System.Collections.Generic.List<Cyclopedia> _dataList;
    
    public TbCyclopedia(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Cyclopedia>();
        _dataList = new System.Collections.Generic.List<Cyclopedia>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Cyclopedia _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Cyclopedia.DeserializeCyclopedia(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Cyclopedia> DataMap => _dataMap;
    public System.Collections.Generic.List<Cyclopedia> DataList => _dataList;

    public Cyclopedia GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Cyclopedia Get(int key) => _dataMap[key];
    public Cyclopedia this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

