
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbLocGame
{
    private readonly System.Collections.Generic.Dictionary<string, LocGame> _dataMap;
    private readonly System.Collections.Generic.List<LocGame> _dataList;
    
    public TbLocGame(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, LocGame>();
        _dataList = new System.Collections.Generic.List<LocGame>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            LocGame _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = LocGame.DeserializeLocGame(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.L10nKey, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, LocGame> DataMap => _dataMap;
    public System.Collections.Generic.List<LocGame> DataList => _dataList;

    public LocGame GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LocGame Get(string key) => _dataMap[key];
    public LocGame this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

