
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbLocUi
{
    private readonly System.Collections.Generic.Dictionary<string, LocUi> _dataMap;
    private readonly System.Collections.Generic.List<LocUi> _dataList;
    
    public TbLocUi(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, LocUi>();
        _dataList = new System.Collections.Generic.List<LocUi>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            LocUi _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = LocUi.DeserializeLocUi(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.L10nKey, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, LocUi> DataMap => _dataMap;
    public System.Collections.Generic.List<LocUi> DataList => _dataList;

    public LocUi GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LocUi Get(string key) => _dataMap[key];
    public LocUi this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

