
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbPartner
{
    private readonly System.Collections.Generic.Dictionary<int, Partner> _dataMap;
    private readonly System.Collections.Generic.List<Partner> _dataList;
    
    public TbPartner(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Partner>();
        _dataList = new System.Collections.Generic.List<Partner>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Partner _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Partner.DeserializePartner(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Partner> DataMap => _dataMap;
    public System.Collections.Generic.List<Partner> DataList => _dataList;

    public Partner GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Partner Get(int key) => _dataMap[key];
    public Partner this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

